title:              Statistician Leboo
email:              lebooian61@gmail.com
description:        A Blog on Statistics, Data Science and Analysis Tips.
author:             Ian Leboo
baseurl:            ""
url:                "https://StatisticianLeboo.github.io"

# Social Profiles
twitter_username:  ian_leboo
github_username: StatisticianLeboo
facebook_username: Ian Leboo
instagram_username: ian_leboo
linkedin_username: Ian-Leboo

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
